#!/bin/sh

set -e

lb config noauto \
	--distribution trixie \
	--architectures amd64 \
	--archive-areas "main contrib non-free-firmware" \
	--apt-recommends false \
	--debian-installer live \
	--debian-installer-gui false \
	"${@}"
